# Generated by Django 4.0.4 on 2024-10-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0031_alter_customer_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
