# Generated by Django 4.0.4 on 2024-10-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pos', '0032_alter_customer_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesanalytics',
            name='cash_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=115),
        ),
        migrations.AlterField(
            model_name='salesanalytics',
            name='total_sales_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=115),
        ),
    ]
